from typing import List

from config import Settings


class SettingsBE(Settings):
    """Backend-specific settings, including stage number and domain."""

    # --- database
    STAGE: int = 0

    DOMAIN: str = "domain.com"
    BE_HOST: str = "http://0.0.0.0:8093"
    BASE_URL: str = "http://localhost"
    FRONTEND_BASE_URL: str = "http://localhost"
    CHECKOUT_PARAMS_SECRET: str = "v5s97e4125h7v4d5x3w"

    # --- test
    URL_RETURN: str = FRONTEND_BASE_URL + "/vpn/payment/personal-account"
    URL_SUCCESS: str = FRONTEND_BASE_URL + "/vpn/payment/success"
    TEST_MODE: bool = True

    # freekassa
    FREEK_PAYMENT_SYSTEM_ID: int = 44
    FREEK_API_URI: str = "https://pay.fk.money/?"
    FREEK_INVOICE_API_URI: str = "https://api.fk.life/v1/orders/create"
    FREEK_URI_DATA_TMPL: str = "{}m={}&oa={}&currency={}&o={}&s={}&lang={}&em={}"
    FREEK_ALLOWED_HOSTS: List[str] = ["127.0.0.1"]

    # freekassa test
    FREEK_SHOP_ID: str = "12345"
    FREEK_API_KEY: str = "99hnghn0ghd9gmdmdgm"
    FREEK_SECRET_1: str = "5d4h57dg5h7mdg"
    FREEK_SECRET_2: str = "fm4f4m24jmfjmfjmfj"

    COOKIE_PASSWORD: str = "dfRJatjOLA6uXFwvfgsH5Lb3ikT1rKSoG0Dp7HfkHJM="

    FIX_EMAILS: dict = {
        "gmail.com": [
            "bmail.com",
            "gail.com",
            "gamil.com",
            "ggmail.com",
            "gimal.com",
            "gmaaail.com",
            "gmaaiil.com",
            "gmaail.co",
            "gmaail.com",
            "gmaeil.com",
            "gmael.com",
            "gmai.cm",
            "gmai.co",
            "gmai.com",
            "gmai9l.com",
            "gmaigmail.com",
            "gmaii.com",
            "gmaiil.com",
            "gmail-mail.com",
            "gmail.adultvidlite.com",
            "gmail.ci",
            "gmail.cim",
            "gmail.cjm",
            "gmail.co",
            "gmail.cokm",
            "gmail.comam",
            "gmail.comc",
            "gmail.comccc",
            "gmail.come",
            "gmail.comgmail.com",
            "gmail.comhello",
            "gmail.coml",
            "gmail.comm",
            "gmail.comnkxlnnxlkk",
            "gmail.comr",
            "gmail.coms",
            "gmail.comtro",
            "gmail.con",
            "gmail.conm",
            "gmail.coom",
            "gmail.cpm",
            "gmail.emlhub.com",
            "gmail.hom",
            "gmail.me",
            "gmail.oom",
            "gmail.vom",
            "gmail0.com",
            "gmail07.com",
            "gmaila.com",
            "gmailc.com",
            "gmaild.com",
            "gmaile.com",
            "gmailgmail.com",
            "gmailk.com",
            "gmaill.com",
            "gmailm.com",
            "gmailo.com",
            "gmailt.com",
            "gmailz.com",
            "gmaim.com",
            "gmainl.com",
            "gmaio.com",
            "gmaip.com",
            "gmaiu.com",
            "gmaiul.com",
            "gmaj.com",
            "gmajil.com",
            "gmal.com",
            "gmall.com",
            "gmaol.com",
            "gmasil.com",
            "gmauil.com",
            "gmaul.com",
            "gmbail.com",
            "gmeil.com",
            "gmfil.com",
            "gmial.com",
            "gmil.com",
            "gmile.com",
            "gmjail.com",
            "gmm.com",
            "gmmail.co",
            "gmmail.com",
            "gmqail.com",
            "gmqil.com",
            "gmsail.com",
            "gmsol.com",
            "gmwil.com",
            "gmzil.com",
            "gnai.com",
            "gnaik.com",
            "gnail.com",
            "hmail.com",
            "jmail.com",
            "qmail.com",
            "gemail.com",
            "goole.com",
            "goooomail.com",
            "jmail.ga",
            "il.comgma",
            "mgail.com",
            "mgial.com",
            "gmail.ru",
            "gmal.ru",
            "gmai.ru",
            "gmaul.ru",
            "gmail.net",
            "gmail.om",
            "gmali.com",
            "gmlail.com",
            "gvail.com",
        ],
        "gmail.it": ["gmal.it"],
        "outlook.com": [
            "oitlook.com",
            "otlook.com",
            "otmail.com",
            "otulook.com",
            "ouitlook.com",
            "oulook.com",
            "oultook.com",
            "outllok.com",
            "outlock.com",
            "outlok.com",
            "outlok.site",
            "outloo.com",
            "outlooc.com",
            "outloog.com",
            "outlooj.com",
            "Outlook.co",
            "outlook.comj",
            "outlookk.com.com",
            "outlookl.com",
            "outlool.com",
            "outloook.com",
            "outloot.com",
            "outlouk.com",
            "outook.com",
            "outool.com",
            "ouylook.com",
            "oytlook.com",
            "uotlook.com",
            "Outlook.con",
        ],
        "outlook.fr": [
            "outloak.fr",
            "outlookl.fr",
            "outlouk.fr",
            "outoo.fr",
            "outook.fr",
        ],
        "outlook.es": ["outlool.es"],
        "outlook.de": ["outook.de"],
        "yandex.ru": [
            "yadnex.ru",
            "andex.ru",
            "yndex.ru",
            "yanbex.ru",
            "uandex.ru",
            "yandex.ru.ru",
            "eandex.ru",
            "iandex.ru",
            "jandex.ru",
            "yandekx.ru",
            "yahdex.ru",
            "yqndex.ru",
            "yandex.ri",
            "eyandex.ru",
            "tandex.ru",
            "yamdex.ru",
            "yande.ru",
            "yanex.ru",
            "yadex.com",
            "yamdex.com",
            "yamdex.ru",
            "yandexmail.com",
            "yanex.com",
            "yadex.ru",
            "yandex.ry",
            "ynadex.ru",
        ],
        "aol.com": ["aol.com.com", "aoo.com", "aol.con", "aol.co"],
        "mail.ru": [
            "maii.ru",
            "mael.ru",
            "mail.ru.ru",
            "meil.ru",
            "maile.ru",
            "maiil.ru",
            "mial.ru",
            "mail.ry",
            "mail.ri",
            "mai.ru",
            "mail.ru\\",
            "maile.ru",
            "mmail.ru",
            "vail.ru",
        ],
        "inbox.ru": ["indox.ru", "invox.ru", "ibnox.ru", "inbox.ry", "inbox.ri"],
        "rambler.ru": [
            "ramler.ru",
            "bambler.ru",
            "ramrler.ru",
            "rambker.ru",
            "ramdler.ru",
            "gambler.ru",
            "rfmbler.ru",
            "ranbler.ru",
            "rambler.ry",
            "rambler.ri",
        ],
        "qq.com": ["qq.con", "qq.cpom", "qq.qq", "qq.yop", "qqd.com", "qq.co"],
        "bk.ru": ["dk.ru", "bk.ry", "bk.ri"],
        "icloud.com": [
            "icloid.com",
            "iclou.com",
            "icloud.com.com",
            "icloud.comw",
            "icloud.con",
            "iclould.com",
            "iclound.com",
            "icloup.com",
            "iclud.com",
            "icooud.com",
            "icoud.com",
            "ickoud.com",
            "iclloud.com",
            "ilcoud.com",
        ],
        "hotmail.com": [
            "ho0tmail.com",
            "homail.com",
            "homtial.com",
            "hootmail.com",
            "hopmail.com",
            "hot.ail.com",
            "hotail.com",
            "hotamil.com",
            "hotemail.com",
            "hotma.com",
            "hotmail.con",
            "hotmait.com",
            "hotmal.com",
            "hotmial.com",
            "hotmil.com",
            "hotmsul.com",
            "hotnail.com",
            "hotrmail.com",
            "jhotmail.com",
            "xn--hotmail-cie.com",
            "hormail.com",
            "hotmail.com.com",
            "hotmmail.com",
        ],
        "hotmail.de": ["hotmil.de", "hotmqil.de"],
        "hotmail.cn": ["hotmali.cn"],
        "hotmail.co.uk": [
            "hormail.co.uk",
            "hotmai.co.uk",
            "hotnail.co.uk",
            "hoymail.co.uk",
        ],
        "hotmail.fr": ["homtail.fr"],
        "gmx.com": ["email.gmx", "t-gmx.com"],
        "mail.com": ["emial.com", "mai.com", "maill.com", "mal.com"],
        "facebook.com": ["facbook.com"],
        "freemail.hu": ["freemai.hu"],
        "protonmail.com": [
            "protomail.com",
            "protommail.com",
            "proton.com",
            "protonmai.com",
            "protonmail.con",
            "protonmail.ru",
            "protonmal.com",
            "protonmil.com",
            "protonnmail.com",
            "protoonmail.com",
            "prrotonmail.com",
        ],
        "tutanota.com": ["totanota.com", "tutanato.com", "tutanote.com"],
        "yahoo.com": [
            "yaoo.com",
            "yhaa.com",
            "yhoo.com",
            "yah.com",
            "yahho.com",
            "yahio.com",
            "yahoo.clm",
            "yahoo.cm",
            "yahoo.con",
            "yahoo.cpm",
            "yahoo.vom",
            "yahoods.com",
            "yahpp.com",
            "uaho.com",
        ],
        "naver.com": ["naver.acom"],
        "ukr.net": ["ukr.nen"],
        "ua.fm": ["ua.fu"],
        "ymail.com": ["ymsil.com", "uymail.com", "ymail.ca"],
        "live.com": ["live.con"],
    }


class SettingsBEDev(SettingsBE):
    # freekassa test
    FREEK_SHOP_ID: str = "12345"
    FREEK_API_KEY: str = "99hnghn0ghd9gmdmdgm"
    FREEK_SECRET_1: str = "5d4h57dg5h7mdg"
    FREEK_SECRET_2: str = "fm4f4m24jmfjmfjmfj"


class SettingsBEProd(SettingsBE):
    # freekassa prod
    FREEK_SHOP_ID: str = "54321"
    FREEK_API_KEY: str = "99hnghn0ghd9gmdmdgm"
    FREEK_SECRET_1: str = "5d4h57dg5h7mdg"
    FREEK_SECRET_2: str = "fm4f4m24jmfjmfjmfj"


settings_ = SettingsBE()
settings = SettingsBEProd() if settings_.PROD == 1 else SettingsBEDev()
